database_path = "db.txt"

[[symbols]]
name = "BTC"
url = "https://api.coingecko.com/api/v3/coins/bitcoin/ohlc?vs_currency=usd&days=1"

[symbols.http_headers]
x-cg-demo-api-key = "${coingecko_api_key}"

[symbols.candle_fields]
timestamp = "$[*][0]"
open = "$[*][1]"
high = "$[*][2]"
low = "$[*][3]"
close = "$[*][4]"


[[symbols]]
name = "ETH"
url = "https://api.coingecko.com/api/v3/coins/ethereum/ohlc?vs_currency=usd&days=1"

[symbols.http_headers]
x-cg-demo-api-key = "${coingecko_api_key}"

[symbols.candle_fields]
timestamp = "$[*][0]"
open = "$[*][1]"
high = "$[*][2]"
low = "$[*][3]"
close = "$[*][4]"