database_path = "db.txt"

[[symbols]]
name = "BTC"
url = "https://api.coingecko.com/api/v3/coins/bitcoin/ohlc?vs_currency=usd&days=1"

[symbols.headers]
x-cg-demo-api-key = "${coingecko_api_key}"

[symbols.fields]
timestamp = "$[-1][0]"
open = "$[-1][1]"
high = "$[-1][2]"
low = "$[-1][3]"
close = "$[-1][4]"


[[symbols]]
name = "ETH"
url = "https://api.coingecko.com/api/v3/coins/ethereum/ohlc?vs_currency=usd&days=1"

[symbols.headers]
x-cg-demo-api-key = "${coingecko_api_key}"

[symbols.fields]
timestamp = "$[-1][0]"
open = "$[-1][1]"
high = "$[-1][2]"
low = "$[-1][3]"
close = "$[-1][4]"